# railway.yml

version: v1
services:
  web:
    image: "python:3.12-slim"
    envs:
      - PORT: "5000"
    buildScript: |
      apt-get update && apt-get install -y nodejs npm
      npm install --prefix client
      npm run build --prefix client
      pip install flask gunicorn
    startCommand: "gunicorn --bind 0.0.0.0:$PORT server.app:app"
    envFile: .env
    # You can add more configuration options here, such as ports, memory limits, etc.
